### ISSUE TITLE
Порядок остановки сервисов

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/facet#3]
@bizywizy @ridhid @Dandi91 @squaredbeaver
В данный момент если A зависит от B и C, а B зависит от C. То при остановке A будет остановлен C и если B что-то хочет делать с C в стопе, то будет фейл. Нужно ли это исправлять? Какие идеи на этот счёт?

**Comment by bizywizy** [comment]
Да, я думаю стоит считать ссылки на сервис или типа того. 
У меня был кейс, когда я запускал N сервисов, которые зависели от БД. После остановки первого был неприятно удивлен, что он убил коннект к БД 😲
Обходился так:
```
async with AsyncExitStack() as stack:
    for service in services:
        await stack.enter_async_context(service)
    await asyncio.gather(*(service.process() for service in services))
```
Конечно, не такое не особо вписывается вообще в паттерн использования facet, но хотелось бы чтобы оно работало.

**Comment by bizywizy** [comment]
@pohmelie
Вот возможная реализация https://github.com/pohmelie/facet/pull/4
