### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Vasiliy566** [pohmelie/facet#7]
Man i do not understand why u created thus service? just for what???

**Comment by Vasiliy566** [comment]
hey author do u have internet?? answer ASAP!!!

**Comment by Vasiliy566** [comment]
bez negativa

**Comment by pohmelie** [comment]
ebalo svoe zakroy poka ya tebe ego ne zakril

**Comment by Vasiliy566** [comment]
project hueta

**Comment by pohmelie** [comment]
ti hueta eptu kloyn!

**Comment by Vasiliy566** [comment]
huki zakrito project vse esche hueta!!!
